### ISSUE TITLE
Block ads

### ISSUE THREAD

**Issue by rex4539** [PaulRBerg/CoinMarketCap-Desktop#1]
CoinMarketCap v1.0.0-stable

Reproducibility: always

Steps:
Launch CoinMarketCap.

What happened:
Ads are shown.

Expected result:
Ads are blocked.

Notes:
Majority of users use Ad Blocker in web browser so they never see ads anyway so seeing in the CoinMarketCap client is degrading the experience.

**Comment by PaulRBerg** [comment]
Thank you Rex for opening the issue. I've just discovered this package: https://www.npmjs.com/package/electron-ad-blocker

I'll try to update the project in the near future.

**Comment by rex4539** [comment]
App is deprecated. Retracting.

**Comment by PaulRBerg** [comment]
Just for the record, I tried to implement electron-ad-blocker but it didn't work well: https://github.com/Jense5/electron-ad-blocker/issues/5

I'm really sorry for deprecating, but maintaining the project became a chore. There has to be an easier way to build desktop apps.
